[package]
name = "rustint"
version = "0.1.1"
authors = ["Marshall Ku <marshall@kakao.com>"]
edition = "2021"
description = "Library for compressing and decompressing DNA sequences"
license = "MIT"
repository = "https://github.com/marshallku/rustint"

[dependencies]
thiserror = "1.0.64"
