name: Deploy to Crates.io

on:
    push:
        branches:
            - master

jobs:
    check-version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.check.outputs.version }}
        steps:
            - uses: actions/checkout@v4
            - name: Check version
              id: check
              uses: marshallku/actions/version/check-cargo@master

    create-tag-release:
        name: Create release
        runs-on: ubuntu-latest
        needs: ["check-version"]
        if: ${{ needs.check-version.outputs.version != '' }}
        outputs:
            tag-exists: ${{ steps.create-tag-release.outputs.tag-exists }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Create tag and release
              id: create-tag-release
              if: ${{ needs.check-version.outputs.version != '' }}
              uses: marshallku/actions/version/generate@master
              with:
                  tag: v${{ needs.check-version.outputs.version }}

    deploy:
        name: Deploy to Crates.io
        runs-on: ubuntu-latest
        needs: ["check-version", "create-tag-release"]
        if: ${{ needs.check-version.outputs.version != '' && needs.create-tag-release.outputs.tag-exists == 'false' }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Build
              run: cargo build --release
            - name: Publish to Crates.io
              run: cargo publish
              env:
                  CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
